// <auto-generated />
namespace OdeToFood.Data.SqlRepository.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class Intializer : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Intializer));
        
        string IMigrationMetadata.Id
        {
            get { return "201412080355565_Intializer"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
